export { FormlyForm } from './components/formly.form';
export { FormlyFieldConfig, FormlyTemplateOptions, FormlyFormOptions } from './components/formly.field.config';
export { FormlyField } from './components/formly.field';
export { FormlyAttributes } from './components/formly.attributes';
export { FORMLY_CONFIG, FormlyConfig, ConfigOption, FormlyExtension } from './services/formly.config';
export { FormlyFormBuilder } from './services/formly.form.builder';
export { FieldType, Field } from './templates/field.type';
export { FieldArrayType } from './templates/field-array.type';
export { FieldWrapper } from './templates/field.wrapper';
export { FormlyModule } from './core.module';
export { defineHiddenProp as ɵdefineHiddenProp } from './utils';
export { reverseDeepMerge as ɵreverseDeepMerge } from './utils';
